<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/assets/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/assets/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/assets/dist/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/assets/plugins/iCheck/square/blue.css">
  <link href="/assets/bower_components/sweetalert/sweetalert.css" rel="stylesheet">

</head>
<body class="" background="/img/bkimg.jpg">
    <div class="login-box">
      <div class="login-logo">
        <a href="/"><b></b>后台</a>
      </div>
      <!-- /.login-logo -->
      <div class="login-box-body">
        <form >
        <input type="hidden" id="token" />
          <div class="form-group has-feedback">
            <input type="text" class="form-control" placeholder="用户名" name="username">
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" class="form-control" placeholder="密码" name="password">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-7">
                <input type="text" class="form-control" placeholder="验证码" name="captcha">
            </div>
            
            <div class="col-xs-3">
                <img src="/auth/captcha"  id = 'checkpic'  onclick="changing();" >
            </div>
          </div>
          <div class="social-auth-links text-center">
              <button type="submit" class="btn btn-primary btn-block btn-flat" id="sub">登录</button>
        </div>
        </form>
        
      </div>
    </div>
<script src="/assets/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/assets/bower_components/sweetalert/sweetalert.min.js"></script>
<!-- iCheck -->
<script src="/assets/plugins/iCheck/icheck.min.js"></script>
<script src="/assets/plugins/form/jquery.form.js"></script>
<script src="/assets/dist/js/api.js"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
    token();

    function changing(){
        document.getElementById('checkpic').src="/auth/captcha?"+Math.random();
    }

    $('form').submit(function() {
        $('#sub').attr("disabled", true).html('登录中...');
        $(this).ajaxSubmit({
            dataType: 'json',
            type: "POST",
            url: "/auth/login",
            success: function (res) {
                if (res.code == 500) {
                    alertMsg('error',res.msg);
                    changing();
                    token();
                    return false;
                }
                window.location.href = res.data.url;
            },
            error: function(e){
                changing();
                token();
                alertMsg('error','登录信息有误');
            },
            complete: function() {
                $('#sub').attr('disabled', false).html('登录');
            }
        });
        return false;
    });

</script>
</body>
</html>
