
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                <h1 class="box-title"><a href="index">菜单管理</a><small>>>子菜单</small></h1>
                </div>

                <form action="addsub" method="post" class="form-horizontal" id = 'signupForm' enctype="multipart/form-data" >
                    <input type="hidden" name="parent_id" value="<?php echo $menuInfo['m_id']; ?>" />
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">上级菜单</label>
                            <div class="col-sm-3">
                            <input type="text" disabled="disabled"  class="form-control input-sm form-control-nowidth input-medium-width" value="<?php echo $menuInfo['m_name']; ?>" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">菜单名称</label>
                            <div class="col-sm-3">
                        <input type="text" name = 'name' class="form-control input-sm form-control-nowidth input-medium-width" id="name">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">控制器名</label>
                            <div class="col-sm-3">
                        <input type="text" name = 'controller' readonly value="<?php echo $menuInfo['m_controller']; ?>" class="form-control input-sm form-control-nowidth input-medium-width" id="controller">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">方法名</label>
                            <div class="col-sm-3">
                            <input type="text" name = 'action' class="form-control input-sm form-control-nowidth input-medium-width" id="action">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">图标</label>
                            <div class="col-sm-3">
                            <input type="text" name = 'icon'  value="" class="form-control input-sm form-control-nowidth input-medium-width" id="icon">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">是否显示菜单</label>
                            <div class="col-sm-2">
                            <select class="form-control" name="display" id="form-field-select-1">
                                <option value="1">是</option>
                                <option value="3">否</option>
                            </select>
                            </div>
                        </div>

                <div class="box-footer">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-6">
                        <div class="btn-group pull-left">
                        <button type="submit" class="btn btn-primary">提交</button>
                        </div>
                        <div> &nbsp<a type="button" href= 'index' class="btn btn-danger">返回</a></div>
                    </div>
                </div>
                
                </form>

            </div>
        </div>
    </div>


<script type="text/javascript">
    $('form').validate({
            // errorElement: 'div',
            errorClass: 'help-block',
            focusInvalid: false,
            rules: {
                name: {
                    required: true,
                    maxlength: 12
                },
                controller: {
                    required: true,
                    maxlength: 20
                },
                action: {
                    required: true,
                    maxlength: 20
                }
            },

            messages: {
                name: {
                    required: "请输入菜单名",
                    maxlength: "菜单名长度不大于12"
                },
                controller: {
                    required: "请输入控制器名",
                    maxlength: "控制器名长度不大于20"
                },
                action: {
                    required: "请输入方法名",
                    maxlength: "方法名长度不大于20"
                }
            },


            highlight: function (e) {
                $(e).closest('.form-group').removeClass('has-info').addClass('has-error');
            },

            success: function (e) {
                $(e).closest('.form-group').removeClass('has-error');//.addClass('has-info');
                $(e).remove();
            },
        });
</script>