<div class="row">
    <div class="box">
        <div class="box-header with-border">
        <h3 class="box-title"><a href="index">菜单管理</a></h3>
        <div class="box-tools">
            <a href="add">
            <button type="button" class="btn bg-maroon margin btn-sm" style="margin-top: 8px;">
              <i class="fa fa-fw fa-plus"></i>新增</button>
            </a>
            </div>
        </div>
        <div class="box-body">
        <div class="table-responsive">
                <table class="table table-bordered table-hover text-center th-center">
                <tr>
                    <th>菜单名</th>
                    <th >控制器</th>
                    <th >方法</th>
                    <th >是否显示</th>
                    <th >操作管理</th>
                </tr>
                <?php echo $treeMenu; ?>
            </table>
        </div>
    </div>
</div>
</div>

<script>
    $('.del').click(function(){
        if (!confirm('确认删除?')) {
            return false;
        }
    });
</script>