    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                <h1 class="box-title"><a href="index">管理员</a><small>>>添加</small></h1>
                </div>

                <form action="add" method="post" class="form-horizontal" id = 'signupForm' enctype="multipart/form-data" >
                    <div class="box-body">
                        <div class="form-group ">
                            <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
                            <div class="col-sm-3">
                                <input type="text" name = 'username' class="form-control input-sm form-control-nowidth input-medium-width" id="username">
                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="inputEmail3" class="col-sm-2 control-label">密码</label>
                            <div class="col-sm-3">
                                <input type="password" name = 'password' class="form-control input-sm form-control-nowidth input-medium-width" id="password" >
                            </div>
                        </div>
                        <div class="form-group ">
                            <label for="inputEmail3" class="col-sm-2 control-label">确定密码</label>
                            <div class="col-sm-3">
                                <input type="password" name = 'confirmpass' class="form-control input-sm form-control-nowidth input-medium-width" id="confirmpass">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">管理员组</label>
                            <div class="col-sm-2">
                            <select class="form-control" name="per" id="form-field-select-1">
                                <option value="">请选择管理员组</option>
                                <?php
                                    foreach ($groupList as $group) {
                                        echo '<option value="'.$group['pg_id'].'">'.$group['pg_name'].'</option>';
                                    }
                                ?>
                                <option value="x">自定义</option>
                            </select>
                            </div>
                        </div>

                        <div class="form-group" style="display:none" id="customized">
                            <label for="inputEmail3" class="col-sm-2 control-label">自定义菜单</label>
                            <div class="table-responsive">
                                 <table class="table table-bordered table-hover text-center th-center">  
                                    <thead>
                                        <tr>
                                            <th width="60px;" class="center">
                                                <label>
                                                    <input type='checkbox' class='ace ace-checkbox-1 chk-all-1'>
                                                    <span class="lbl"></span>
                                                </label>
                                            </th>
                                            <th>菜单名</th>
                                            <th >控制器</th>
                                            <th >方法</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                            <?php echo $treeMenu; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                <div class="box-footer">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-6">
                        <div class="btn-group pull-left">
                        <button type="submit" class="btn  btn-primary" >提交</button>
                        </div>
                        <div> &nbsp<a type="button" href= 'index' class="btn btn-danger">返回</a></div>
                    </div>

                </div>
                </form>

            </div>
        </div>
    </div>
<script type="text/javascript">
    $('form').validate({
            // errorElement: 'div',
            errorClass: 'help-block',
            focusInvalid: false,
            rules: {
                username: {
                    required: true,
                    rangelength: [2, 12]
                },
                password: {
                    required: true,
                    rangelength: [6, 20]
                },
                confirmpass: {
                    required: true,
                    equalTo: '#password'
                },

                per: {
                    required: true,   
                }

            },

            messages: {
                username: {
                    required: "请输入用户名",
                    rangelength: "用户名长度2~12"
                },
                password: {
                    required: "请输入密码",
                    rangelength: "密码长度6~20"
                },
                confirmpass: {
                    required: "请再次输入密码",
                    equalTo: "两次密码输入不一致"
                },
                per: {
                    required: "自少选择一个分组",
                }
            },


            highlight: function (e) {
                $(e).closest('.form-group').removeClass('has-info').addClass('has-error');
            },

            success: function (e) {
                $(e).closest('.form-group').removeClass('has-error').addClass('has-success');
                $(e).remove();
            },
        });

        $('#form-field-select-1').on('change',function(){
            if($(this).val() == 'x') {
                $('#customized').show();
            } else {
                $('#customized').hide();
            }
        });

        var chkAll={};
        chkAll.run = function(all, items){
        all.on('click', function (){
            if(all.is(':checked')){
                items.each(function(){
                    this.checked = true;
                });
            }else{
                items.each(function (){
                    this.checked = false;
                });
            }
        });

        items.on('click', function(){
            if(! $(this).is(':checked')){
                all.prop('checked', false);
            }else{
                if(items.length == items.filter(':checked').length){
                    all.prop('checked', true);
                }
            }
        });
    };
    chkAll.run($('.chk-all-1'), $('.chk-item-1'));
    $('input[type="checkbox"]').click(function(){
    var pid = $(this).attr('pid');
    var pObj = $('#'+pid);
    if (pid == 0) {
        var thisId = $(this).attr('id');
        if ($(this).is(':checked')) {
            $('input[type="checkbox"][pid='+thisId+']').each(function(){
                this.checked = true;
            });
        }else{
            $('input[type="checkbox"][pid='+thisId+']').each(function(){
                this.checked = false;
            });
        }
    }

    if (!pObj.is(':checked') && $(this).is(':checked')) {
        pObj.prop('checked', true);
    }
});
</script>