    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                <h1 class="box-title"><a href="authlist">管理员</a><small>>>编辑</small></h1>

                </div>

                <form action="edit" method="post" class="form-horizontal" id = 'signupForm' enctype="multipart/form-data" >
                    <div class="box-body">

                        <div class="form-group ">
                            <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
                            <div class="col-sm-3">
                                <input type="text" name = 'username'  value="<?php echo $info['u_name']; ?>" class="form-control input-sm form-control-nowidth input-medium-width" id="username">
                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="inputEmail3" class="col-sm-2 control-label">密码</label>
                            <div class="col-sm-3">
                                <input type="password" name = 'password'  class="form-control input-sm form-control-nowidth input-medium-width" id="password" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">管理员组</label>
                            <div class="col-sm-2">
                            <select class="form-control" name="groupid" id="form-field-select-1">
                                <option value="0">请选择管理员组</option>
                                <?php
                                    foreach ($groupList as $group) {
                                        $selected = $info['u_permi'] == $group['pg_id'] ? 'selected="selected"' : '';
                                        echo '<option '.$selected.' value="'.$group['pg_id'].'">'.$group['pg_name'].'</option>';
                                    }
                                ?>
                                <option value="x" <?=$permi['pg_custom'] == 1 ? 'selected="selected"' : '' ?> >自定义</option>
                            </select>
                            </div>
                        </div>
             
                        <div class="form-group" id="customized" style="display: <?=$permi['pg_custom'] == 1 ? 'off':'none'?>">
                            <label for="inputEmail3" class="col-sm-2 control-label">自定义菜单</label>
                            <div class="col-sm-5">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th width="60px;" class="center">
                                                <label>
                                                    <input type='checkbox' class='ace ace-checkbox-1 chk-all-1'>
                                                    <span class="lbl"></span>
                                                </label>
                                            </th>
                                            <th>菜单名</th>
                                            <th >控制器</th>
                                            <th >方法</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                            <?php echo $treeMenu; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                <input type="hidden" name="id" value="<?php echo $info['u_id']; ?>">
                <div class="box-footer">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-6">
                        <div class="btn-group pull-left">
                        <button type="submit" class="btn  btn-primary  ">提交</button>
                        </div>
                        <div> &nbsp<a type="button" href= 'index' class="btn btn-danger">返回</a></div>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>





<script type="text/javascript">

    $('form').validate({
            errorClass: 'help-block',
            focusInvalid: false,
            rules: {
                username: {
                    required: true,
                    rangelength: [2, 12]
                },
                password: {
                    rangelength: [6, 20]
                },
            },

            messages: {
                username: {
                    required: "请输入用户名",
                    rangelength: "用户名长度2~12",
                },
                password: {
                    rangelength: "密码长度6~20",
                },
            },


            highlight: function (e) {
                $(e).closest('.form-group').removeClass('has-info').addClass('has-error');
            },

            success: function (e) {
                $(e).closest('.form-group').removeClass('has-error');//.addClass('has-info');
                $(e).remove();
            },
        });


        $('#form-field-select-1').on('change',function(){
            if($(this).val() == 'x') {
                $('#customized').show();
            } else {
                $('#customized').hide();
            }
        });

        var chkAll={};
        chkAll.run = function(all, items){
        all.on('click', function (){
            if(all.is(':checked')){
                items.each(function(){
                    this.checked = true;
                });
            }else{
                items.each(function (){
                    this.checked = false;
                });
            }
        });

        items.on('click', function(){
            if(! $(this).is(':checked')){
                all.prop('checked', false);
            }else{
                if(items.length == items.filter(':checked').length){
                    all.prop('checked', true);
                }
            }
        });
    };
    chkAll.run($('.chk-all-1'), $('.chk-item-1'));
    $('input[type="checkbox"]').click(function(){
    var pid = $(this).attr('pid');
    var pObj = $('#'+pid);
    if (pid == 0) {
        var thisId = $(this).attr('id');
        if ($(this).is(':checked')) {
            $('input[type="checkbox"][pid='+thisId+']').each(function(){
                this.checked = true;
            });
        }else{
            $('input[type="checkbox"][pid='+thisId+']').each(function(){
                this.checked = false;
            });
        }
    }

    if (!pObj.is(':checked') && $(this).is(':checked')) {
        pObj.prop('checked', true);
    }
});
</script>