    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                <h3 class="box-title"><a href="index">管理员组</a>
                  <small>>>添加</small></h3>
                </div>
                <form action="add" method="post" class="form-horizontal" id = 'signupForm'>
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">管理员组名</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" name="groupName" id="groupName">
                            </div>
                        </div>
                    </div>

                <div class="box-footer">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-6">
                        <div class="btn-group pull-left">
                        <button type="submit" class="btn btn-primary ">提交</button>
                        </div>
                        <div> &nbsp<a type="button" href= 'index' class="btn btn-danger">返回</a></div>
                    </div>

                </div>
                </form>
            <div>
        </div>
    </div>
<script type="text/javascript">
    $('form').validate({
            errorClass: 'help-block',
            focusInvalid: false,
            rules: {
                groupName: {
                    required: true,
                    rangelength: [1,12],
                },
            },

            messages: {
                groupName: {
                    required: "请输入管理员组名",
                    rangelength: "管理员组名长度1~12"
                },
            },

            highlight: function (e) {
                $(e).closest('.form-group').removeClass('has-info').addClass('has-error');
            },

            success: function (e) {
                $(e).closest('.form-group').removeClass('has-error');//.addClass('has-info');
                $(e).remove();
            },
        });
</script>