
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/assets/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/assets/bower_components/select2/dist/css/select2.min.css">
  <link rel="stylesheet" href="/assets/dist/css/AdminLTE.min.css">
  <link href="/assets/bower_components/sweetalert/sweetalert.css" rel="stylesheet">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="/assets/dist/css/skins/_all-skins.min.css">
  <script src="/assets/bower_components/jquery/dist/jquery.min.js"></script>
  <script src="/assets/plugins/laydate/laydate.js"></script>
  <script src="/assets/bower_components/sweetalert/sweetalert.min.js"></script>
  <script src="/assets/plugins/form/jquery.form.js"></script>
  <script src="/assets/plugins/form/jquery.validate.min.js"></script>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="/index" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>
      <!-- <img src="/img/logo.jpg" /> -->
      </b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b></b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Control Sidebar Toggle Button -->
            <li>
              <a href="/admin/binding">
                  <i class="fa fa-paw mr5"></i>
                  二次绑定
              </a>
            </li>
            <li>
              <a href="/admin/pwd">
                  <i class="fa fa-unlock-alt mr5"></i>
                  修改密码
              </a>
            </li>
            <li class= 'logout'>
              <a href="/auth/logout">
                  <i class="fa fa-sign-out mr5 "></i>
                  安全退出
              </a>
            </li>
          <li>
            <a href="#"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <ul class="sidebar-menu" data-widget="tree">
        <li class="<?php echo $controller == "index" ? 'active' : ''?>">
              <a href="/index/index">
                <i class="fa fa-dashboard"></i> <span>工作台</span>
              </a>
        </li>

        <?php foreach ($menus as $menu) : ?>
          <li class="treeview <?php echo $menu['m_controller'] == $controller ? 'active' : ''?>">
            <a href="#">
              <i class="fa <?=$menu['m_icon']?>"></i> <span><?php echo $menu['m_name'] ?: ''; ?>
              <?php if($menu['m_name'] == "申请管理" && ($applyGroupTotal > 0 || $applyTotal > 0)) { ?>
                <span class="pull-right-container">
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <i class="fa fa-circle-o text-red"></i>
                </span>
              <?php  } else  { ?>
           
              </span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
              <?php }  ?>

            </a>
            <ul class="treeview-menu ">
              <?php foreach ($menu['sub'] as $m) :  ?>
                <li class="<?php 
                if ($_menuInfo['m_dis'] == 1) {
                  echo ($controller == $m['m_controller'] && $action == $m['m_action']) ? 'active' : '';
                }
                else {
                  echo $_menuInfo['m_parent_id'] == $m['m_id'] ? 'active' : '';
                }
                ?>"
                >
              <a href="/<?=$m['m_controller']?>/<?=$m['m_action']?>"><i class="fa <?=$m['m_icon']?>"></i> <?php echo $m['m_name'] ?: ''; ?> 
               <?php 
                if($m['m_name'] == "入驻列表" && $applyGroupTotal > 0) { ?> 
                  <small class="label pull-right bg-red"><?=$applyGroupTotal?>
              <?php }?>  
              <?php 
                if($m['m_name'] == "申请列表" && $applyTotal > 0) { ?> 
                  <small class="label pull-right bg-red"><?=$applyTotal?>
              <?php }?>  
                </small>
                </span></a></li>
              <?php endforeach; ?>
            </ul>
          </li>
        <?php endforeach ?>
        </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <section class="content-header">
  
    </section>
    <!-- Main content -->
    <section class="content">
      <?=$this->view->getContent(); ?>
      <!-- Small boxes (Stat box) -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2020 </strong>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab"></div>    
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->
<!-- jQuery UI 1.11.4 -->
<script src="/assets/bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="/assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/assets/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/assets/dist/js/adminlte.min.js"></script>

<!-- AdminLTE for demo purposes -->
<script src="/assets/dist/js/demo.js"></script>
<script src="/assets/dist/js/api.js"></script>
<script src="/assets/dist/js/home.js"></script>

</body>
</html>
